import React from 'react'
import './globals.css'

import NavBar from './components/NavBar'
export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
  }

export default function RootLayout ({children}) {
  return (
    <html lang="en">
    <body>
      <nav>
        <a href="/meals">Home</a>
        <a href="/meals/add">Add Meal</a>
        <a href="meals/summary">Summary</a>
      </nav>
      <div className="container">
        {children}
      </div>
      <footer>NutriSnap © 2025. Built with 💚 for Health & Simplicity.</footer>
    </body>
  </html>
    
  )
}
